# Generated by Django 4.1.6 on 2023-07-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.CharField(default='Sin película', max_length=40),
        ),
    ]
